#!/bin/zsh

#Install Homebrew

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

#Run these two commands after successful installation to add Homebrew to your PATH
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/vinu.joseph/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

#Install git

brew install git
echo "========================================"
echo "🤖👉👉👉👉👉 INSTALLED GIT 👈👈👈👈👈🤖"
echo "========================================"
