#!/bin/zsh

# Core
brew install \
  docker-compose \
  diff-so-fancy \
  git-gui \
  vim \
  yarn &&
echo "======================================================="
echo "🤖👉👉👉👉👉 INSTALLED MAIN HOMEBREW CORE 👈👈👈👈👈🤖"
echo "======================================================="

# Optional Core
brew install \
 maven &&
echo "==========================================================="
echo "🤖👉👉👉👉👉 INSTALLED OPTIONAL HOMEBREW CORE 👈👈👈👈👈🤖"
echo "==========================================================="

# Cask
brew install --cask \
  google-chrome \
  firefox \
  rectangle \
  visual-studio-code \
  iterm2 \
  slack \
  vlc \
  postman \
  appcleaner \
  the-unarchiver \
  monitorcontrol \
  microsoft-teams \
  shottr \
  
echo "=================================================="
echo "🤖👉👉👉👉👉 INSTALLED HOMEBREW CASK 👈👈👈👈👈🤖"
echo "=================================================="