#!/bin/zsh

#Install Homebrew, Core and Cask

chmod +x brewfile-po
./brewfile-po
echo "=================================================================="
echo "🤖👉👉👉👉👉  RUN BREWFILE - INSTALLED CORE AND CASK 👈👈👈👈👈🤖"
echo "=================================================================="

chmod +x open-cask
./open-cask
echo "=============================================="
echo "🤖👉👉👉👉👉 OPEN ALL INSTALLED CASKS 👈👈👈👈👈🤖"
echo "=============================================="