#!/bin/zsh

#Google Chrome
sudo xattr -dr com.apple.quarantine /Applications/Google\ Chrome.app
open /Applications/Google\ Chrome.app

#Firefox
sudo xattr -dr com.apple.quarantine /Applications/Firefox.app
open /Applications/Firefox.app

#Rectangle
sudo xattr -dr com.apple.quarantine /Applications/Firefox.app
open /Applications/Rectangle.app

#Visual Studio Code
sudo xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code.app
open /Applications/Visual\ Studio\ Code.app

#iTerm2
sudo xattr -dr com.apple.quarantine /Applications/iTerm.app
open /Applications/iTerm.app

#Slack
sudo xattr -dr com.apple.quarantine /Applications/Slack.app
open /Applications/Slack.app

#VLC
sudo xattr -dr com.apple.quarantine /Applications/VLC.app
open /Applications/VLC.app

#Postman
sudo xattr -dr com.apple.quarantine /Applications/Postman.app
open /Applications/Postman.app

#AppCleaner
sudo xattr -dr com.apple.quarantine /Applications/AppCleaner.app
open /Applications/AppCleaner.app

#The-Unarchiver
sudo xattr -dr com.apple.quarantine /Applications/The\ Unarchiver.app
open /Applications/The\ Unarchiver.app

#MonitorControl
sudo xattr -dr com.apple.quarantine /Application/MonitorControl.app
open /Applications/MonitorControl.app

#Microsoft Teams
sudo xattr -dr com.apple.quarantine /Application/Microsoft\ Teams.app
open /Applications/Microsoft\ Teams.app/

#Shottr
sudo xattr -dr com.apple.quarantine /Application/Shottr.app
open /Applications/Shottr.app

echo "=============================================="
echo "🤖👉👉👉👉👉 OPENED ALL HOMEBREW CASK 👈👈👈👈👈🤖"
echo "=============================================="